export const BASE_URL = 'http://192.168.0.101:8085';

export const ROUTES = {
    CATEGORY_ALL: '/category/all-category',
    ACCEPT_STATUSES: '/access/all-status',
    UPLOAD_VIDEO: '/video/upload',
    ALL_VIDEO: '/video/all',
    GET_LIKES: '/grade/countlike',
    GET_DISLIKES: '/grade/countdislike',
    GET_COMMENTS: '/comment/all',
    GET_VIEWS: '/grade/count_watched',
    ADD_COMMENT: '/comment/add-comment',
    ADD_LIKE: '/grade/like',
    GET_VIDEO: '/video/',
    IS_LIKED: '/grade/liked',
    IS_DISLIKED: '/grade/disliked',
    SEND_LIKE: '/grade/like',
    SEND_DISLIKE: '/grade/dislike',
    IS_SUBSCRIBED: '/grade/subscribed',
    TOGGLE_SUBSCRIPTION: '/subs/toggle-subscription',
    CREATE_PLAYLIST: '/playlist/create-playlist',
    ALL_PLAYLISTS: '/playlist/user-playlists',
    ALL_PLAYLISTS_FOR_VIDEO: '/playlist/for-video',
    ADD_VIDEO_TO_PLAYLIST: '/list_video/add-video-playlist',
};
